## tests/test_mpri_set_d_table.cg -- GAP master script
## MPRIA - GNU Multi-Precision Rational Interval Arithmetic Library
## Copyright (C) 2009-2016  Jerome Benoit <jgmbenoit@rezozer.net>
##
## This file is part of the GNU MPRIA Library.
##
## The GNU MPRIA Library is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## The GNU MPRIA Library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with the GNU MPRIA Library.  If not, see <http://www.gnu.org/licenses/>.
##

MPRIAMasterFileNameComment:=function() return ("not human readable"); end;;

Read("mpria_test.gi");
if (IsBound(MPRIAMasterFileName) and (MPRIAMasterFileName <> fail)) then

listof_bits:=[
	10,
	24,
	32,
	36,
	41,
	46,
#	53,
#	113,
#	256,
#	512,
#	1024,
	];

SetFloats(MPFR,53);
listof_candidate:=[
	0.0,
	FLOAT.PI,
	FLOAT.E,
	1.0/FLOAT.E,
	];

Compacted(listof_candidate);

Apply(listof_candidate,x->Reversed(Set([-x,+x])));
listof_candidate:=Flat(listof_candidate);

## preamble
MPRIACInputOpen();

## amble
MPRIACInputWriteTestTableLineBEGIN();

for cdx in listof_candidate do
	for bits in listof_bits do
		for surrounding in listof_SurroundingMode do
			AppendTo(CInputStream,
				"\t{",
				HexStringifyFloat(cdx),",",
				String(bits),",",
				stringify_SurroundingMode(surrounding),",",
				SeqStringifyListOfNum(compute_float_interval(cdx,bits,surrounding)),
				"},\n"
				);
		od;
	od;
od;

MPRIACInputWriteTestTableLineEND(
	Concatenation("{",HexStringifyFloat(0.0),",0,MPRI_SRND_BCAA,NULL,NULL}")
	);

## postamble
MPRIACInputClose();

fi;
QUIT;
##
## vim:syntax=gap
##
## End of file tests/test_mpri_set_d_table.cg
