## tests/test_mpri_set_qi_q_table.cg -- GAP master script
## MPRIA - GNU Multi-Precision Rational Interval Arithmetic Library
## Copyright (C) 2009-2016  Jerome Benoit <jgmbenoit@rezozer.net>
##
## This file is part of the GNU MPRIA Library.
##
## The GNU MPRIA Library is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## The GNU MPRIA Library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with the GNU MPRIA Library.  If not, see <http://www.gnu.org/licenses/>.
##

MPRIAMasterFileNameComment:=function() return ("not human readable"); end;;

Read("mpria_test.gi");
if (IsBound(MPRIAMasterFileName) and (MPRIAMasterFileName <> fail)) then

listof_bits:=[
	10,
	24,
	53,
	113,
	256,
	512,
	1024,
	];

listof_candidate:=[
	[+4/7,0,+2/23],
	[+3/5,41/7,+2/101],
	[+1/17,23/7,+2/11],
	[-118184/17,13967553600/293,55440/18289],
	[-118184/17,13967553600/293,2520/18289],
	[-118184/17,13967553600/293,1162885459773267804109536000/2521],
	];

Compacted(listof_candidate);

Apply(listof_candidate,c->[
	[+c[1],c[2],+c[3]],
	[+c[1],c[2],-c[3]],
	[-c[1],c[2],+c[3]],
	[-c[1],c[2],-c[3]]
	]);
fotsil_candidate:=[];
Perform(listof_candidate,function(c) Append(fotsil_candidate,c); end);
listof_candidate:=fotsil_candidate;

## preamble
MPRIACInputOpen();

## amble
MPRIACInputWriteTestTableLineBEGIN();

for cdx in listof_candidate do
	for bits in listof_bits do
		for surrounding in listof_SurroundingMode do
			AppendTo(CInputStream,
				"\t{",
				SeqStringifyListOfNum(cdx),",",
				String(bits),",",
				stringify_SurroundingMode(surrounding),",",
				SeqStringifyListOfNum(compute_quadratic_irrational_interval(cdx[1],cdx[2],cdx[3],bits,surrounding)),
				"},\n"
				);
		od;
	od;
od;

MPRIACInputWriteTestTableLineEND("{NULL,NULL,NULL,0,MPRI_SRND_BCAA,NULL,NULL}");

## postamble
MPRIACInputClose();

fi;
QUIT;
##
## vim:syntax=gap
##
## End of file tests/test_mpri_set_qi_q_table.cg
