## tests/test_mpri_sqrt_table.cg -- GAP master script
## MPRIA - GNU Multi-Precision Rational Interval Arithmetic Library
## Copyright (C) 2009-2016  Jerome Benoit <jgmbenoit@rezozer.net>
##
## This file is part of the GNU MPRIA Library.
##
## The GNU MPRIA Library is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## The GNU MPRIA Library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with the GNU MPRIA Library.  If not, see <http://www.gnu.org/licenses/>.
##

MPRIAMasterFileNameComment:=function() return ("not human readable"); end;;

Read("mpria_test.gi");
if (IsBound(MPRIAMasterFileName) and (MPRIAMasterFileName <> fail)) then

listof_bits:=[
	10,
	24,
	53,
	113,
	256,
	512,
	1024,
	];

listof_candidate:=[
	[0,0],
	[+2,+3],
	[+1/3,+1/2],
	[+25/49,+49/25],
	[+41/7,43/7],
	[+7927/13967553600,+7933/13967553600],
	[+13967553601/13967553600,+13967553637/13967553600],
	];

## preamble
MPRIACInputOpen();

## amble
MPRIACInputWriteTestTableLineBEGIN();

for cdx in listof_candidate do
	for bits in listof_bits do
		expected_lep:=compute_quadratic_irrational_interval(0,cdx[1],1,bits,BestConvergentAtLeft);
		expected_rep:=compute_quadratic_irrational_interval(0,cdx[2],1,bits,BestConvergentAtRight);
		expected_lep:=expected_lep[1];
		expected_rep:=expected_rep[2];
		AppendTo(CInputStream,
			"\t{",
			SeqStringifyListOfNum(cdx),",",
			String(bits),",",
			SeqStringifyListOfNum([expected_lep,expected_rep]),
			"},\n"
			);
	od;
od;

MPRIACInputWriteTestTableLineEND("{NULL,NULL,0,NULL,NULL}");

## postamble
MPRIACInputClose();

fi;
QUIT;
##
## vim:syntax=gap
##
## End of file tests/test_mpri_sqrt_table.cg
